on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
name: my-workflow
jobs:
  run-tests:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test
